# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d11e3ac5a2a6bc8755ed4031c269fbbe82f71640d679cbe92f3a47b70b75037f219f8e6ec0abdbdf17c582c5f015bf38ef1825e3702b95653c0ca8276728f23a
  twitter_required: false # set to true and fill in credentials (apps.twitter.com)
  consumer_key :
  consumer_secret :
  access_token :
  access_token_secret :

test:
  secret_key_base: 01fc305d2352705806c5688e9f9e2344799abdeae60c95dd9bd5953a66e2ae94cadb5f5a89996382a681a01d45f6e8dd12129dc764b5ae5ccf71bb972e374629

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
